feat: sync Shopify payouts
ParsimonyGit/erpnext pull request #6
Opened 2020-10-27 11:00 UTC by Alchez

2020-10-27 11:01 UTC, vjFaLk commented
Task linked: [CU-dyv5zx Investigate Shopify Payment API](https://app.clickup.com/t/dyv5zx)

2020-11-04 12:07 UTC, vjFaLk commented
Task linked: [CU-1k7v8t Poll Shopify's API to retrieve payouts and make payments every day](https://app.clickup.com/t/1k7v8t)

2020-12-02 12:00 UTC, vjFaLk commented
Task linked: [CU-1k7uu2 Add disclaimer in Shopify Settings to enable "Shopify Payments" on the Shopify admin and private app pages](https://app.clickup.com/t/1k7uu2)

2021-01-13 13:51 UTC, vjFaLk requested changes
Partial review.

2021-01-13 13:51 UTC, vjFaLk commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +	frappe.flags.request_id = request_id
What's this about?

2021-01-13 13:51 UTC, vjFaLk commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +	if not order.get("financial_status") in ["paid", "partially_refunded", "refunded"]:
Should we do these check in `sync_sales_order` instead? In fact, the function name is also inaccurate as it's not just the Order is it? Maybe it should be `sync_shopify_data`?

2021-01-13 13:51 UTC, vjFaLk commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +		sales_order = get_shopify_document("Sales Order", cstr(order['id']))
`order.get()` for safety

2021-01-13 13:51 UTC, vjFaLk commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +				item.discount_percentage = 100
Why discount, why not just rate?

2021-01-13 13:56 UTC, vjFaLk commented
Task linked: [CU-1k99w5 Poll Shopify's API to retrieve payouts and make payments every day](https://app.clickup.com/t/1k99w5)

2021-01-13 14:00 UTC, Alchez commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +	frappe.flags.request_id = request_id
If a request fails, they use scheduler events to retry. The request ID is used as context here.

2021-01-13 14:01 UTC, Alchez commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +				item.discount_percentage = 100
It gets overriden on validate for some reason. Discounts are the only way to maintain the zero rate.

2021-01-18 12:11 UTC, vjFaLk commented on erpnext/erpnext_integrations/connectors/shopify_connection.py
> +	shopify_settings = frappe.get_doc("Shopify Settings")
Use `get_single`

2021-01-28 13:19 UTC, Alchez commented
Moved to https://github.com/ParsimonyGit/shopify_integration.

2021-01-28 13:19 UTC, closed without merging