fix: backlink PR and PO on inter company transfer from DN
ParsimonyGit/erpnext pull request #80
Opened 2023-12-13 12:44 UTC by bhattdevarsh

![po-pr](https://github.com/ParsimonyGit/erpnext/assets/58166671/b0a90a86-f89d-4086-982e-d518ebb7d7ff)

2023-12-13 12:49 UTC, bhattdevarsh commented
Task linked: [CU-86cu3f11k [EVA] PR's created from the Inter -company Delivery Notes are not getting linked to the Original PO](https://app.clickup.com/t/86cu3f11k)

2023-12-14 08:29 UTC, Alchez requested changes

2023-12-14 08:29 UTC, Alchez commented on erpnext/stock/doctype/delivery_note/delivery_note.py
> +		return doclist
This will only process the first item and return

2023-12-14 08:29 UTC, Alchez commented on erpnext/stock/doctype/delivery_note/delivery_note.py
> +			filters={"parent": purchase_order_reference},
This is a small optimization, but check if `purchase_order_reference` exists, otherwise it'll return all POs, I think

2023-12-14 09:25 UTC, Alchez approved these changes

2023-12-14 09:26 UTC, merged